version: '3'

networks:
  webapp_main:

services:
  nginx_main:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
    - "85:80"
    links:
      - app_main
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - app_main
    networks:
      - webapp_main

  app_main:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
        - db_main
    working_dir:  /var/www/app
    container_name: ${APP_NAME}_app
    volumes:
      - ./:/var/www/app
      - ./docker/supervisor/conf/:/etc/supervisor/conf.d/
      - ./docker/supervisor/conf/supervisord.conf:/etc/supervisor/supervisord.conf
    #command: systemctl start supervisor
    ports:
      - "9002:9000"
    networks:
      - webapp_main

  db_main:
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD:  ${DB_PASSWORD}
    ports:
      - 8102:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: ${APP_NAME}_mysql
    networks:
      - webapp_main

  phpmyadmin_main:
    depends_on:
      - db_main
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST:  db_main
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1
    networks:
        - webapp_main
    container_name: ${APP_NAME}_phpmyadmin



